[project]
name = "pfig"
version = "0.1.0"
description = "Paper Figure utilities."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.7",
    "polars>=1.35.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[tool.pytest.ini_options]
testpaths = ["pfig", "tests"]
python_files = ["test_*.py", "test.py"]
python_functions = ["test_*"]
addopts = "--durations=5 -m 'not slow'"
pythonpath = ["."]
filterwarnings = []
markers = ["slow: marks tests as slow to run, and thus skipped by default"]
